# This will help run robot framework and newman in the git hub actions
name: Testing Framework
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          mkdir Test
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        # Install newman
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
        # Install Python
      - name: Install Python
        uses: actions/setup-python@v5.1.0
        # Install RobotFramework
      - name: Install RobotFramework
        run: |
          pip install robotframework
          pip install robotframework-jsonlibrary
        # Run test
      - name: Run Test
        run: robot TestingFW.robot
        # Check Test Results
      - name: Check test results
        id: check-results
        run: |
          if [ -f Report/JSON/newman_report.json ]; then
            fails=$(jq '.run.failures | length' Report/JSON/newman_report.json)
            if [ "$fails" -gt 0 ]; then
              echo "Test failures found: $fails"
              exit 1
            else
              echo "No test failures"
            fi
          else
            echo "Report/JSON/newman_report.json not found"
            exit 1
          fi
        # Send email on pass/fail
        # On Pass
      - name: Send email notification on success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Build Success"
          body: "The build has succeeded!"
          from: ${{ secrets.SMTP_FROM }}
          to: rhitam.bhattacharya@eximietas.design 
          attachments: |
            Report/HTML/report.html
            Report/JSON/newman_report.json
        # On Fail    
      - name: Send email notification on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Build Failure"
          body: "The build has failed!"
          from: ${{ secrets.SMTP_FROM }}
          to: rhitam.bhattacharya@eximietas.design
          attachments: |
            Report/HTML/report.html
            Report/JSON/newman_report.json
